language: php

php:
  - 5.4
  - 5.5
  - hhvm

env:
  global:
    - PLUGIN_NAME=DiffbotSource
    - PLUGIN_PATH=Plugin/DiffbotSource
    - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
    - DB=mysql
    - CAKE_VERSION=2.4
    - secure: BoFh4lbp/LCweOvKtpjhaHZTpL7Q4vPsL5NwNUUKk0rlXBS9kORs6X6SCW9kudXp+O41sQiS+krsLHCrW+ldJvDXl/K2bojmzi3QbExITWIN/jqPBIWbuD2pVNNyN2MynMuhoHsJWX6Dd9TfgA/euvq9N6738dmF+zxL6dMI7vE=

  matrix:
    - CAKE_VERSION=2.3
    - CAKE_VERSION=2.4
    - CAKE_VERSION=2.5

matrix:
  include:
    - php: 5.5
      env:
        - COVERALLS=1
    - php: 5.5
      env:
        - PHPCS=1
    - php: 5.5
      env:
        - FOC_VALIDATE=1
    - php: 5.5
      env:
        - PHPDOC=1

script:
  - if [ "$PHPDOC" = 1 ] ; then
      if [ "$PHPDOC" != 1 ] || [ "$GH_TOKEN" = "" ]; then exit 0; fi;
    fi;
  - mkdir -p $HOME/build/docs;
  - ./cakephp/app/vendor/bin/phpdoc -d . -t $HOME/build/docs --template ./cakephp/app/vendor/phpdocumentor/templates/responsive-twig
  - if [ "$?" -gt 0 ]; then exit 1; fi

notifications:
  email: skuridin-alex@ya.ru
