language: php
php:
- 5.4
- 5.5
- hhvm
env:
  global:
  - PLUGIN_NAME=DiffbotSource
  - PLUGIN_PATH=Plugin/DiffbotSource
  - REQUIRE="imsamurai/cakephp-environment:dev-master phpdocumentor/phpdocumentor:2.*"
  - DB=mysql
  - CAKE_VERSION=2.4
  - secure: CtCjmj4EOL8dzB7RgM3fWvTBSuzuZ4fWI6f1UK7cXrzzghu3LvkIpfPdj6pZnilHM3ibwYzcCNCt9Hwmy8ysbjEcyA3/hGj00TMGNpujBhiUdmgIM3B8ryer/NLxzWGdt2IM15O5vtNV9WUMFH+uKmRgovRpAM8vRxmm+RetOCc=
  matrix:
  - CAKE_VERSION=2.3
  - CAKE_VERSION=2.4
  - CAKE_VERSION=2.5
matrix:
  include:
  - php: 5.5
    env:
    - COVERALLS=1
  - php: 5.5
    env:
    - PHPCS=1
  - php: 5.5
    env:
    - FOC_VALIDATE=1
  - php: 5.5
    env:
    - PHPDOC=1
before_script:
- chmod +x ./travis/*
- ./travis/before_script.sh
script:
- ./travis/script.sh
after_success:
- ./travis/after_success.sh
notifications:
  email: skuridin-alex@ya.ru
